
package formacaojava;

public class EscopoVariavel {
    public static void main(String [] args)
    { 
         // aqui a variável i não existe
         int i = 5;
         // a partir daqui ela existe
        while (condicao) {
            // o i ainda vale aqui
             int j = 7;
           // o j passa a existir
           }
       // aqui o j não existe mais, mas o i continua dentro do escopo
 
    }    
}
